language: php

dist: trusty
sudo: false

php:
    - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-dist

script:
  - echo "CI passed succesfully"
