language: php

sudo: required

dist: trusty

php:
  - 7.1

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - vendor/bin/phpcs -p --standard=PSR2 --ignore="vendor,resources,storage,public,node_modules,database,bootstrap" ./
  - mysql -e 'create database meteoraspi;'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.dusk.testing .env
  - php artisan key:generate
  - php artisan migrate --force
  - php artisan db:seed
  - php artisan passport:install
  - php artisan set:client_secret .env
  - npm install
  - node_modules/.bin/tslint --project tsconfig.json
  - php artisan serve &

script:
  - npm run test
  - php artisan dusk

notifications:
  email: false
  slack:
    rooms:
      secure: QHVrAysZ2zvQVRwG9X3PiX9IZagqxh81k9AhfEKrvFNhfMAzi+EOGon4unsDBYmS0ZWOdt2lsDlHSUXCeCPzRssTYo/Qn/Gbo8YJEECCIZXXInBFPwV5L0rvB61PW4WYf8duWtInSBAfWqB2EuhVuabdNgC8OVcfo7JCibrrnD0z25xo3n1Nl0/IF8OlFOsnp9VhWw4moUHNR1st2Uu+/RPdSe1wotrt+klSwQqDY+INWiV/GKQq/0RLYxynWRk9Yq27ArYn1AA7v3Ha9hT2DzgS/T9pTdCt7P03J17jV6Mebi/XJgKHWcKzNmAxdPgN08d58tgdtUlQxUQJ7oxFgrEiqBVGTzobBi/u68Zr2dr8bOc8c5eI42ktjht7SpLZvIWjPERWAj7XnKw2JUlcHfcEYSAlnbzZ3b2a+UcksYSuCyynVtAEza4cs4XRR2dXx54arK/24njQ/1bCNpbH/kCMopupdyZJnT+0iaPe+1TenDLYpXVYts4xz9P8RyzmOR1s1YQg6ehG/LbpTv8Hq3TN5QzLUV8SCpS/M2xSaREJiIN3nXnDUwvlb7RavCxXQ83ZffCF9r9XYsHv8t8tIUTaTsrzE6Yg9G26vcJUJ6QxnMy9YyYVXScHnEoK63bcJTTP+CEqJRhYJOeeDz87Aobw9azcZVuEeYvGUOvErug=
    on_success: change
    on_failure: always
