export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const WEATHER_LOAD_START = "WEATHER_LOAD_START";
export const WEATHER_LOAD_SUCCESS = "WEATHER_LOAD_SUCCESS";
export const WEATHER_LOAD_FAIL = "WEATHER_LOAD_FAIL";
export const CHART_LOAD_SUCCESS = "CHART_LOAD_SUCCESS";
